### ISSUE TITLE
Editor cursor position

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#149]
I moved browser tab with active editor from one screen to another. The gizmo doesn't match the cursor position anymore.
Seems like some cursor offset is not updated. DPI scaling and different resolutions might play a role.

**Comment by ErlerPhilipp** [comment]
opening debug console (chrome) also triggers this issue

**Comment by sophie-sudoku** [comment]
[ready for testing]: i pushed the fix to develop

**Comment by ErlerPhilipp** [comment]
@sophie-sudoku didn't solve the problem for me. seems less off since the cursor is at least in the correct window. when i move the editor to the left screen, the cursor seems to have a ~400 pixel offset to the right.

**Comment by ErlerPhilipp** [comment]
@ertz10 this is still open. maybe you have an idea

**Comment by ErlerPhilipp** [comment]
seems to work after all. maybe it just wasn't pushed to the live system
